# Generated by Django 2.2 on 2019-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('idioma', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
