# Generated by Django 2.2 on 2019-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('A', 'Arte y cultura'), ('B', 'Bares y vida nocturna'), ('C', 'Naturaleza y deportes'), ('D', 'Comida y restaurantes'), ('E', 'Compras')], max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('idioma', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
