# Generated by Django 2.2 on 2019-04-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiatour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Arte', 'Arte y cultura'), ('Bares', 'Bares y vida nocturna'), ('Natu', 'Naturaleza y deportes'), ('Comida', 'Comida y restaurantes'), ('Compras', 'Compras')], max_length=100),
        ),
    ]
