# Generated by Django 2.2 on 2019-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiatour', '0004_auto_20190429_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='idioma',
            field=models.CharField(choices=[('Esp', 'Español'), ('Ing', 'Ingles'), ('Gua', 'Guarani'), ('Esp_Ing', 'Español e ingles'), ('Esp_Ing_Gua', 'Español, ingles y guarani'), ('Esp_Ing', 'Español y Guarani')], max_length=100),
        ),
    ]
