# Generated by Django 2.2 on 2019-04-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiatour', '0005_auto_20190429_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guiatour.Ciudad'),
        ),
    ]
