# Generated by Django 2.2 on 2019-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiatour', '0007_auto_20190430_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
