# Generated by Django 2.2 on 2019-04-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiatour', '0008_auto_20190430_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='actividad',
            name='guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guiatour.Guia'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
